# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: ./client
    container_name: frontend
    networks:
      - app-network
    expose:
      - "5173"

  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-network
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge